### ISSUE TITLE
Add ability to provide AWS region when authenticating

### ISSUE THREAD

**Issue by itsderek23** [opstower-ai/llm-opstower#3]
Otherwise, it defaults to using us-east-1.

**Comment by ashwinkpes** [comment]
Please provide support to Mumbai regionif possible

**Comment by itsderek23** [comment]
You can now set your AWS region:

```
llm keys set opstower --value AWS_ACCESS_KEY_ID:AWS_SECRET_ACCESS_KEY:AWS_REGION
```

For example, replace `AWS_REGION` with `ap-south-1`. 

If no region is provided, this will default to use `us-east-1` as the region.

**Comment by ashwinkpes** [comment]
Perfect...thanks this really would help.

Regards,
Ashwin
